create database Restaurant_Finder;
\c restaurant_finder;
create table restaurant(R_id varchar primary key,Name varchar,Type varchar,Cuisine varchar,Opening_time time,Closing_time time);
create table customer(C_id varchar primary key,Cname varchar,Phno numeric(10,0),Street varchar,City varchar,State varchar,Zip numeric(6,0),E_id varchar);
create table delivery(Dno numeric(4,0) primary key,Ddate date,Dtime time,Dprice integer,C_id varchar,R_id varchar);
create table review(Title varchar,Content varchar,Rating numeric(1,1),C_id varchar,R_id varchar);
create table orders(O_id varchar primary key,Qty integer,I_id varchar,E_id varchar);
create table bill(B_id varchar primary key,Time_stamp timestamp,Total_without_tax numeric(6,2),O_id varchar,C_id varchar,Total_with_tax numeric(6,2));
create table employee(E_id varchar primary key,E_name varchar,E_Phno numeric(10,0),State varchar,Street varchar,Zip numeric(6,0),Date_of_Join date,R_id varchar,Role varchar);
create table menu(I_id varchar primary key,I_name varchar,I_price numeric(5,0),R_id varchar);
create table reservation(T_no numeric(3,0),Status varchar,Capacity numeric(2,0),R_Code varchar primary key,C_id varchar);
create table restaurant_contact(R_id varchar,Phno numeric(10,0));
create table restaurant_address(R_id varchar,Street varchar,City varchar,State varchar,Zip varchar);
create table employee_contact(E_id varchar,Phno numeric(10,0));
create table customer_eats(R_id varchar,C_id varchar);
create table restaurant_reservation(R_id varchar,R_Code varchar);
create table customer_order(C_id varchar,O_id varchar);
create table order_menu(O_id varchar,I_id varchar);

alter table customer Add Foreign key(E_id) References employee(E_id) on delete cascade;
alter table delivery Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table delivery Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table review Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table review Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table orders Add Foreign Key(E_id) References employee(E_id) on delete cascade;
alter table orders Add Foreign Key(I_id) References menu(I_id) on delete cascade;
alter table bill Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table bill Add Foreign Key(O_id) References orders(O_id) on delete cascade;
alter table employee Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table reservation Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table restaurant_contact Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table restaurant_address Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table employee_contact Add Foreign Key(E_id) References employee(E_id) on delete cascade;
alter table customer_eats Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table customer_eats Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table restaurant_reservation Add Foreign Key(R_id) References restaurant(R_id) on delete cascade;
alter table restaurant_reservation Add Foreign Key(R_Code) References reservation(R_Code) on delete cascade;
alter table customer_order Add Foreign Key(C_id) References customer(C_id) on delete cascade;
alter table customer_order Add Foreign Key(O_id) References orders(O_id) on delete cascade;
alter table order_menu Add Foreign Key(O_id) References orders(O_id) on delete cascade;
alter table order_menu Add Foreign Key(I_id) References menu(I_id) on delete cascade;
alter table restaurant_contact Add Primary Key(R_id,Phno) ;
alter table restaurant_address Add Primary Key(R_id,Zip); 
alter table employee_contact Add Primary Key(E_id,Phno) ;
alter table customer_eats Add Primary Key(R_id,C_id) ;
alter table restaurant_reservation Add primary key(R_id,R_Code) ;
alter table customer_order Add primary key(C_id,O_id) ;
alter table order_menu Add primary key(O_id,I_id);

